# STEP 1 -  BUILD JS PROD BUNDLE
FROM node:alpine as builder
RUN apk update && apk add --no-cache
COPY . .
RUN npm i
RUN npm run build

# STEP 2 -  SERVE BUNDLE W/ NGINX
FROM nginx:alpine
## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*
## From 'builder' copy website to default nginx public folder
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
