# STEP 1 -  BUILD JS PROD BUNDLE
FROM node:alpine as builder
RUN apk update && apk add --no-cache
COPY .  /app
RUN cd /app && npm i && npm run build

# STEP 2 -  SERVE BUNDLE W/ NGINX
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/ /usr/share/nginx/html
RUN ls /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
